apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: login
spec:
  inputs:
    resources:
      - name: repo
        type: git
    params:
      - name: USER
        description: Login username
        default: 'developer'
        type: string
      - name: PASS
        description: Login password
        default: 'developer'
        type: string
      - name: SERVER_URL
        description: The access point for the cluster.
        default: 'https://gpu-compute-001.infra.prod.upshift.rdu2.redhat.com:8443'
  outputs:
    resources:
      - name: build-image
        type: image
steps:
  - name: login
    image: openshift-client
    command: ["oc", "login", "-u", "$(inputs.params.USER)", "-p", "$(inputs.params.PASS)", "(inputs.params.SERVER_URL)"]