apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: image-classification
spec:
  resources:
    - name: repo
      type: git
    - name: build-image
      type: image

  params:
    - name: USER
      description: Login username
      default: 'rlevinso'
      type: string
    - name: PASS
      description: Login password
      type: string
    - name: SERVER_URL
      description: The access point for the cluster.
      default: 'https://gpu-compute-001.infra.prod.upshift.rdu2.redhat.com:8443'
    - name: TEMPLATE
      description: The remplate for the run job
      type: string
      default:
      - "image_classification_template.yaml"

  tasks:
    - name: login
      taskref:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: ARGS
          value: ["login", "-u", "$(params.USER)", "-p", "$(params.PASS)", "(params.SERVER_URL)"]
    - name: prebuild
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: ARGS
          value: ['new-build', '$(resources.repo)', '--context-dir=image_classification/tensorflow']
      resources:
        inputs:
          - name: source
            resource: repo
        outputs:
          - name: image
            resource: build-image
    - name: build
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: ARGS
          value: ['start-build', 'training']
      resources:
        inputs:
          - name: image
            resource: build-image
            from: 
              - prebuild
    - name: run
      taskRef:
        name: run
        kind: ClusterTask
      params:
        - name: TEMPLATE
          value: '$(params.TEMPLATE)'
      runAfter:
        - build