---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: repo
spec:
  type: git
  params:
    - name: url
      value: https://github.com/raynalee4/training.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: build-image
spec:
  type: image
  params:
    - name: url
      value: docker-registry.default.svc:5000/mlperf/training:latest
---
