apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: run
spec:
  inputs:
    resources:
    - name: build-image
      type: image
  steps:
    - name: run
    - image: $(inputs.resources.build-image.url)
      workingDir: /workspace/
      securityContext:
        privileged: false
      command: ["/bin/sh", "./run_and_time.sh"]