apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: run
spec:
  inputs:
    resources:
    - name: image
      type: image
  steps:
    - name: run
      image: $(inputs.resources.image.url)
      workingDir: /workspace/
      securityContext:
        privileged: true
      command: ["/bin/sh", "./run_and_time.sh"]