apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: run
spec:
  inputs:
    resources:
    - name: image
      type: image
  steps:
    - name: ls-top
      image: $(inputs.resources.image.url)
      workingDir: /workspace/source
      securityContext:
        privileged: true
      command: ["ls", "/workspace/source"]
    - name: run
      image: $(inputs.resources.image.url)
      workingDir: /workspace/source
      securityContext:
        privileged: true
      command: ["/bin/sh", "./image_classification/tensorflow/run_and_time.sh"]
